### ISSUE TITLE
[Feature request] could you add a new function.

### ISSUE THREAD

**Issue by blackcodersec** [xnl-h4ck3r/knoxnl#10]
Hi there,
Could you add a new function? like, when we are using this script with lots of URLs. 
There are only 5k api request, which is very low.
Think like your input's list line 7k+.
If all api requests are finished.
Then script will be waiting for new day for new api request.

I think it would to great feature.

**Comment by xnl-h4ck3r** [comment]
Hi @blackcodersec. Thanks for using knoxnl and taking the time to raise a suggestion. That is certainly something that is needed! I'll have a think about the best way to achieve that.

**Comment by xnl-h4ck3r** [comment]
Hi @blackcodersec. I believe this was addressed with the introduction of the `-pur`/`--pause-until-reset` argument a while back so I will clode this issue.
