### ISSUE TITLE
Fails with Session.request()

### ISSUE THREAD

**Issue by wr3nch0x1** [xnl-h4ck3r/knoxnl#12]
[ ERR! ] - (GET)  https://brutelogic.com.br/xss.php?a=1  KNOXSS ERR: Session.request() got an unexpected keyword argument 'reties'

**Comment by wr3nch0x1** [comment]
You have mistyped the ```retries``` in `https://github.com/xnl-h4ck3r/knoxnl/blob/a57fe922fd8341791c52c157aef745980b04177c/knoxnl/knoxnl.py#L264`

**Comment by xnl-h4ck3r** [comment]
Hi @wr3nch0x1. Thanks so much for letting me know! Apologies for that. I have corrected that now. Many thanks

**Comment by xnl-h4ck3r** [comment]
Apologies, I;m not sure how that passed testing! I mist have been running a different version. I have backed out for now. Thank you

**Comment by wr3nch0x1** [comment]
@xnl-h4ck3r requests library does not have the retries in-built. I have modified the code to make it work. I have raised the PR, Can you please check once? Cheers 

https://github.com/xnl-h4ck3r/knoxnl/pull/13
