### ISSUE TITLE
[Feature Request] Resume Option

### ISSUE THREAD

**Issue by ShebinJoseJacob** [xnl-h4ck3r/knoxnl#14]
Is it possible to add a resume option similar to ProjectDiscovery tools?

**Comment by xnl-h4ck3r** [comment]
Hi @ShebinJoseJacob, thanks for using knoxnl and taking the time to raise a suggestion.
I haven't actually seen the Project Discovery resume option in practice, but as far as I'm aware, it generates a new file and you can then use that again if you use that file as input (or using `-resume`)
Urless currently wirtes the links that haven't been tried yet to a new file with a `.todo` suffix. Then you can use that as input the next time you run (with `-i`). Can you describe what you want to happen, if it's more than it does already?
Many thanks

**Comment by ShebinJoseJacob** [comment]
Hello @xnl-h4ck3r, I appreciate your response. The resume feature in ProjectDiscovery tools generates a new file that saves the index of the last attempted URL as a checkpoint. This allows us to use the resume file as input to continue running from the last saved checkpoint. Previously, I had the impression that **knoxnl** only added failed URLs (those returning errors) to the .todo file. However, as you pointed out, if it adds all untried URLs along with failed ones, then it's exactly what I need. Thank you for developing and open-sourcing such fantastic tools.

**Comment by xnl-h4ck3r** [comment]
Awesome! Good luck finding something good :)
