### ISSUE TITLE
stop due to errors issues!!

### ISSUE THREAD

**Issue by blackcodersec** [xnl-h4ck3r/knoxnl#16]
your idea is good, and the script as well. but I think this idea is very bad. because I have an API request, but this function just stops the process and makes *****.todo files. which is weird to use this script again and again. could you make the new function to force the request to complete the file scan?

![image](https://github.com/xnl-h4ck3r/knoxnl/assets/72689232/d397fd4b-b1b7-478d-842f-72ee8528fe2c)

**Comment by blackcodersec** [comment]
any update boss?

**Comment by xnl-h4ck3r** [comment]
Hey @blackcodersec . Sorry, I seemed to miss this one. The errors that occur can be related to the KNOXSS API, and carrying on processing could potentially be a waste of time and better to run again later.
Can you run with `-v` next time, and if there are specific errors that have caused it to stop, then let me know what they were? If there are errors that turn out to be target specifc rather that the API then I'll make sure they don't cause it to stop

**Comment by blackcodersec** [comment]
If 6-10 errors are found in the output knoxnl auto stops the process and creates a new file which is filename.************.todo.
If I run **********.todo file for scanning again, I see the same thing happen again. and creating a new file filename.************.todo.************.todo. It is too big a name file, there is no option where I can set the name value for *****.todo file.

But I want here that if the requests get the error while scanning, the scan will be full.
I hope you understand, if not, feel free to comment.

![image](https://github.com/xnl-h4ck3r/knoxnl/assets/72689232/b17c9de1-3208-424c-ae23-783fe47d0301)

**Comment by xnl-h4ck3r** [comment]
Hey @blackcodersec . Thanks for raising an issue. The problem with the filename getting bigger has been fixed in the latest version I released yesterday.
If I do any code changes, then I will update the version for 2 reasons: People won't know there is a later version if I keep it the same, and the code change would have been done for a reason, AND in order to upload any change to PyPi (so can intall with pip), it has to be a unique version number. 
Thanks

**Comment by blackcodersec** [comment]
hey @xnl-h4ck3r,
Ok, 
But I want here that if the requests get the error while scanning, the scan will be full.

Is it possible boss?

**Comment by xnl-h4ck3r** [comment]
Sorry, I don't fully understand what you are asking. Do you mean that even if there are errors with the API, that you want it to continue even though they're likely to fail?

**Comment by blackcodersec** [comment]
Yes, there is no API error, sometimes some subdomain blocks knoxss IP, so it shows some error, but if knoxnl finds more than 6-10 times error, knoxnl stops auto scan. which is bad (I think)
Because some subdomains won't accept Knoxss IP but other links will be accepted. but knoxnl did not check that urls. knoxnl makes a file which is ****.todo

**Comment by xnl-h4ck3r** [comment]
It shouldn't stop on those errors. In your example screenshot it stopped because it was failing to connect to KNOXSS itself rather than issues with the targets through the API.
Can you send me a screenshot of a new run where it stops because of a target blocking KNXOSS or something to do with the target? I'm not sure how to replicate the issue

**Comment by blackcodersec** [comment]
Check the image. knoxss IP blocking issue here,
![image](https://github.com/xnl-h4ck3r/knoxnl/assets/72689232/0094180f-edf1-4b99-a12a-6c8a0df72e18)

**Comment by xnl-h4ck3r** [comment]
Ho @blackcodersec . Again the last errors that caused it to stop were the API timing out and then being unable to establick a connection to the API. If we can't contact the API, everything would fail if we carry on,
I'm unsure why there are issues connecting to the API at that time

**Comment by xnl-h4ck3r** [comment]
I'll look into this more to try anf figure out the issue

**Comment by blackcodersec** [comment]
I think it would be good. another thing is, I think knoxss server config is not good. most of the time url not scanned fully.

**Comment by blackcodersec** [comment]
I am asking to Knoxss, and he told me, now Knoxss has to handle a lot of requests, so sometimes there are problems with requests.

> I'm thinking of making a change that will pause for 30 seconds if one of these API issues happen, and then try again. Maybe have an argument for the amount of retries and seocnds to wait, and default to 3 and 30 seconds respectively. What do you think?

That's why, I think it would be good.

**Comment by xnl-h4ck3r** [comment]
> How to avoid this type of error? I think if you implement retries scan, when a URL will not be scanned or error will occur. It would be great update.
> 
> ![image](https://private-user-images.githubusercontent.com/72689232/320612381-3ecc537a-23ee-4958-9f45-c939cc86f949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MDM1MTgsIm5iZiI6MTcxMjYwMzIxOCwicGF0aCI6Ii83MjY4OTIzMi8zMjA2MTIzODEtM2VjYzUzN2EtMjNlZS00OTU4LTlmNDUtYzkzOWNjODZmOTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDE5MDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMjM0NzFkZTQyYzUxNzk5YzczYTRmMzUzZWEyNjVmMWMyZmNhYTMzMGJjMmYzYjRmMWEzOTUwMWFkYzlkYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qkk_8_u3BrWJ7iYIMQP7-I8vdauA2ZMHYMSZF_HOcaw)

Hi @blackcodersec, I think is is related with an issue with the KNOXSS API itself. It happens when there is a runtime error of `failed to establish a new connection` when trying to call the API. It can occur if you are running low on memory (which has happened for some people on limited VPS running lots of other things), but it is most likely an issue with the KNOXSS API. So bascially, there is nothing we are able to do with that. There are changes coming soon that will wait for a while and do a number of retries if errors like this happen.

**Comment by Nishantbhagat57** [comment]
@xnl-h4ck3r 
```
 _           _ ___    __      _
| | ___ __   V_V\ \  / /_ __ | | 
| |/ / '_ \ / _ \\ \/ /| '_ \| | 
|   <| | | | (_) / /\ \| | | | | 
|_|\_\_| |_|\___/_/  \_\_| |_|_| 
                 by @Xnl-h4ck3r 

Current knoxnl version 4.0 (latest)

NOTE: Overriding "API_KEY" from config.yml with passed API Key xxxx-aa8d-xxxx-8a3c-xxxx

Calling KNOXSS API for 6852 targets...

[ SAFE ] - (GET)  https://stage-gr-en-origin.test.test.com/ [51/5000]
[ SAFE ] - (GET)  https://bcassets.test.com/FUZZ [52/5000]
[ ERR! ] - (GET)  https://storeship-dev.test.com/FUZZ  KNOXSS ERR: Target is blocking KNOXSS IP [52/5000]
[ SAFE ] - (GET)  https://daq.test.com.tw/ [53/5000]
The KNOXSS service is currently unavailable. Please try again later.
[ ERR! ] - (GET)  https://np-msapi.test.com/FUZZ  KNOXSS ERR:  [53/5000]
[ ERR! ] - (GET)  https://www.load-mid-management.test.com/#/.  KNOXSS ERR:  [53/5000]

API calls made so far today - 53/5000

Had to stop due to errors. All unchecked URLs have been written to /home/nishant57/BB/test.com/xsstest/urls.txt.20240415_145750.todo

The following domains seem to be blocking KNOXSS and might be worth excluding for now: storeship-dev.test.com
No successful XSS found... better luck next time! 🤘

```

**Comment by xnl-h4ck3r** [comment]
Hi @Nishantbhagat57. It stopped because there was an issue with the KNOXSS API. Unfortunatley there is much I can do if the API is having issues. I am working on a change to wait for a while when the API is having problems to try again a few times before stopping.
