### ISSUE TITLE
Excessive amount of timeouts

### ISSUE THREAD

**Issue by j0hnZ3RA** [xnl-h4ck3r/knoxnl#17]
In recent days, I've been receiving a gigantic amount of timeouts from knoxnl. I don't know why, but even with different hosts (I've tested on more than 5), it always returns timeouts, timeouts. I no longer see requests marked as (SAFE) or (XSS), only ERR! and the reason is timeout. However, the same URL that I just received a timeout for, when I go to the graphical interface, it says that it just couldn't identify XSS, meaning it's (SAFE), it doesn't return a timeout. And the same URL, if I try directly via the API using CURL, also doesn't return any error, just that it didn't identify XSS.

Do you think there might be a problem related to knoxnl? Is anyone else having this kind of issue? Do you know how to solve it?

![Captura de tela 2024-04-04 010137](https://github.com/xnl-h4ck3r/knoxnl/assets/82909572/37292161-a5cc-430b-a6a2-2db284623981)

![Captura de tela 2024-04-04 010538](https://github.com/xnl-h4ck3r/knoxnl/assets/82909572/71e48b43-273a-474b-bec2-2e7e7538e528)

![Captura de tela 2024-04-04 010702](https://github.com/xnl-h4ck3r/knoxnl/assets/82909572/204b3359-e503-4ec5-8a8c-71e6053e25e4)

It's worth mentioning that I've already done various tests with many different hosts; it's not just in this specific case. Lately, the only host I've been successful with is testphp.vulnweb.com ):

With it, I don't have problems with timeouts, but with any other host, that's all I've been getting.

**Comment by xnl-h4ck3r** [comment]
Hi @j0hnZ3RA. Thanks for taking the time to raise an issue. When you see `KNOXSS ERROR: The target website times out`, that is actually the KNOXSS API responding with that error. So I'm not sure why it would timeout with a request from knoxnl, but not when you use curl.
Is there any way you can send me an example URL that does this? I understand you won't want to post here, but could you send my via DM on Twitter or Discord? I will not share with anyone, but will need to test it to try and reproduce the issue. I understand if you can't though

**Comment by j0hnZ3RA** [comment]
Hi @xnl-h4ck3r. I sent it to you in Twitter DMs, thank you!

**Comment by xnl-h4ck3r** [comment]
Hi @j0hnZ3RA. As mentioned in twitter, this is to do with the `--timeout` value being too low. 
For the beneift of anyone else looking at this issue, you can set `-t 600` for example, and this should resolve the issue of timeouts. 
I am working on a change to set the default to 600 seconds instead of 180 seconds, and also allow a value of 0 that will effectibely mean no timeout.
