### ISSUE TITLE
Enhancement: Write the successful find to output file

### ISSUE THREAD

**Issue by sumgr0** [xnl-h4ck3r/knoxnl#3]
Hi!

I've been testing the tool and really like how it can help in automating the knoxss to the workflow.

I've noticed, that when I'm running the tool on a file with output tag, the successful discoveries are not saved until the complete of the task. So incase I've to cancel the run mid way using Ctrl+c the output file is empty.

Hope this can be a quick implement.

Thanks

**Comment by xnl-h4ck3r** [comment]
Hey @sumgr0. For some reason I never got altered to this issue, so I've only just seen it!! Sorry about not getting back to you earlier! I'll add it to the list!

**Comment by sumgr0** [comment]
Hahaha... sometimes notifications are lost in the cyberspace. No worries at all.

**Comment by xnl-h4ck3r** [comment]
Hey @sumgr0, I've looked into making a change to do this, but it looks like it already does. As soon as it finds a successful result it writes it to the file. I tested and it seems to work fine. Have you tried since then and get the same problem?

**Comment by xnl-h4ck3r** [comment]
Hi @sumgr0, just wondering if you saw my last comment and still had this issue?

**Comment by sumgr0** [comment]
Oh yes, I was able to figure it out. Missed to close this earlier.

Thank you for the follow-up
