### ISSUE TITLE
need a new script!

### ISSUE THREAD

**Issue by blackcodersec** [xnl-h4ck3r/knoxnl#7]
Big Fan xnl-h4ck3r,
Can you make a new script for Burpsuite? We use Burpsuite most of the time for website testing. So if there is an extension for Burpsuite, that will scan any request. I think it will be very helpful.

**Comment by xnl-h4ck3r** [comment]
Hi @blackcodersec. Thanks! Have you read the secion in the README for Burp https://github.com/xnl-h4ck3r/knoxnl#using-in-burp-suite-proxy ? You can use the Piper extension to call knoxnl for a request. Is that was you needed?

**Comment by blackcodersec** [comment]
sorry sorry, I didn't saw it before. thanks for your  reply. I will try this things.

**Comment by blackcodersec** [comment]
what is the issue here?
![image](https://github.com/xnl-h4ck3r/knoxnl/assets/72689232/5ca3ac48-6c9d-4b4b-bd30-b60e6eedd325)

**Comment by xnl-h4ck3r** [comment]
Hi @blackcodersec. I'm not sure. The error "KNOXSS can't test it (forbidden)" is returned by the KNOXSS API, so it is something happening on that side. Maybe try to run the same URL on the GUI on knoxss.me, and see if it gives you more information?

**Comment by blackcodersec** [comment]
Thanks for your help. I am closing this issue.
