### ISSUE TITLE
Handling Output Saving on Ctrl+C Interruption (Question)

### ISSUE THREAD

**Issue by 0xPugazh** [xnl-h4ck3r/knoxnl#8]
HI @xnl-h4ck3r 
I'm running scans in huge number of urls, but sometimes I find myself needing to interrupt the process using Ctrl+C before it completes. I'm wondering what happens to the output in such cases. Does knoxnl save any partial results, or is all progress lost upon interruption?

**Comment by xnl-h4ck3r** [comment]
Hi @0xPugazh, thanks for using the tool and taking the time to raise an issue. Knoxnl doesn't currently save partial resilts unfortunately :(
I will add it to the TODO list, but I'm not sure when that will get completed

**Comment by 0xPugazh** [comment]
Thanks for your reply.
